id: I6446F150
ocr_import_info:
  bdrc_scan_id: W4PD2014
  source: bdrc
  ocr_info:
    timestamp: '2023-02-01T00:00:00Z'
  batch_id: batch-0002
  software_id: norbuketaka
  expected_default_language: bo
  op_import_options: null
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-03-08 20:14:07.247177
last_modified: 2023-02-01 00:00:00+00:00
parser: https://github.com/OpenPecha/Norbu-Keta-eText-import/blob/main/norbu_ketaka_parser.py
source_metadata:
  id: http://purl.bdrc.io/resource/W4PD2014
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW4PD2014
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དམ་ཆོས་དགོངས་པ་གཅིག་པའི་ཀར་ཊཱིཀ་ཆེན་མོ།
  languages:
  - bo
  author: ཀརྨ་པ ༠༨་མི་བསྐྱོད་རྡོ་རྗེ།
bases:
  I2PD20585:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD20585
      total_pages: 440
      volume_number: 1
      volume_pages_bdrc_intro: 2
    base_file: I2PD20585.txt
    order: 1
  I2PD20587:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD20587
      total_pages: 532
      volume_number: 3
      volume_pages_bdrc_intro: 2
    base_file: I2PD20587.txt
    order: 2
  I2PD20588:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD20588
      total_pages: 562
      volume_number: 4
      volume_pages_bdrc_intro: 2
    base_file: I2PD20588.txt
    order: 3
  I2PD20589:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD20589
      total_pages: 470
      volume_number: 5
      volume_pages_bdrc_intro: 2
    base_file: I2PD20589.txt
    order: 4
  I2PD20586:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD20586
      total_pages: 418
      volume_number: 2
      volume_pages_bdrc_intro: 2
    base_file: I2PD20586.txt
    order: 5
copyright:
  status: Public domain
  notice: The proofread texts are donated by the Norbu Ketaka project led by Queenie
    Luo (Harvard University), Zhiying Li (Sichuan University) and Leonard van der
    Kuijp (Harvard University). Correspondence should be directed to  queenieluo@g.harvard.edu
license: CC0
